#!/usr/bin/python

import os
import sys
from thumbor.crypto import Signer

if (len(sys.argv) == 2):
    path = sys.argv[1]
elif (len(sys.argv) == 3):
    size = sys.argv[1]
    url = sys.argv[2]
    path = size + '/' + url
else:
    print ('Usage: ' + sys.argv[0] + ' [size] url')
    exit(1)

with open(os.path.dirname(os.path.abspath(__file__))+'/thumbor.key') as f:
    key = f.read().rstrip()

signer = Signer(key)

resultApi = 'https://api.gbif.org/v1/image/'.encode('utf-8') + signer.signature(path) + '/'.encode('utf-8') + path.encode('utf-8')

print (resultApi)
